// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_START = 'fetch_start';
export const FETCH_ERROR = 'fetch_error';

// Spinner
export const HIDE_SPINNER = "HIDE_SPINNER";
export const SHOW_SPINNER = "SHOW_SPINNER";

//Mappe
export const GET_MAPPA = "GET_MAPPA";
export const GET_MAPPA_SUCCESS = "GET_MAPPA_SUCCESS";
//Grafici
export const GET_DATIGRAFICO = "GET_DATIGRAFICO";
export const GET_DATIGRAFICO_SUCCESS = "GET_DATIGRAFICO_SUCCESS";

//Statistiche
export const STATISTICHE = "STATISTICHE";
export const STATISTICHE_SUCCESS = "STATISTICHE_SUCCESS";
export const STATISTICHE_ALLERTE_DETTAGLIO = "STATISTICHE_ALLERTE_DETTAGLIO";
export const STATISTICHE_ALLERTE_DETTAGLIO_SUCCESS = "STATISTICHE_ALLERTE_DETTAGLIO_SUCCESS";
export const STATISTICHE_FRODI = "STATISTICHE_FRODI";
export const STATISTICHE_FRODI_SUCCESS = "STATISTICHE_FRODI_SUCCESS";
export const STATISTICHE_FRODI_DETTAGLIO = "STATISTICHE_FRODI_DETTAGLIO";
export const STATISTICHE_FRODI_DETTAGLIO_SUCCESS = "STATISTICHE_FRODI_DETTAGLIO_SUCCESS";
export const STATISTICHE_RITIRI = "STATISTICHE_RITIRI";
export const STATISTICHE_RITIRI_SUCCESS = "STATISTICHE_RITIRI_SUCCESS";
export const STATISTICHE_RITIRI_DETTAGLIO = "STATISTICHE_RITIRI_DETTAGLIO";
export const STATISTICHE_RITIRI_DETTAGLIO_SUCCESS = "STATISTICHE_RITIRI_DETTAGLIO_SUCCESS";

//Newsletter
export const SEARCH_NEWSLETTER = "SEARCH_NEWSLETTER";
export const SEARCH_NEWSLETTER_SUCCESS = "SEARCH_NEWSLETTER_SUCCESS";

//Norme const
export const GET_NORMA = "GET_NORMA";
export const GET_NORMA_SUCCESS = "GET_NORMA_SUCCESS";
export const GET_LIST_NORME = "GET_LIST_NORME";
export const GET_LIST_NORME_SUCCESS = "GET_LIST_NORME_SUCCESS";
export const SEARCH_NORME = "SEARCH_NORME";
export const SEARCH_NORME_SUCCESS = "SEARCH_NORME_SUCCESS";

//Allerte const
export const GET_ALLERTA = "GET_ALLERTA";
export const GET_ALLERTA_SUCCESS = "GET_ALLERTA_SUCCESS";
export const GET_LIST_ALLERTE = "GET_LIST_ALLERTE";
export const GET_LIST_ALLERTE_SUCCESS = "GET_LIST_ALLERTE_SUCCESS";
export const SEARCH_ALLERTE = "SEARCH_ALLERTE";
export const SEARCH_ALLERTE_SUCCESS = "SEARCH_ALLERTE_SUCCESS";

//Sentenze const
export const GET_SENTENZA = "GET_SENTENZA";
export const GET_SENTENZA_SUCCESS = "GET_SENTENZA_SUCCESS";
export const GET_LIST_SENTENZE = "GET_LIST_SENTENZE";
export const GET_LIST_SENTENZE_SUCCESS = "GET_LIST_SENTENZE_SUCCESS";
export const SEARCH_SENTENZE = "SEARCH_SENTENZE";
export const SEARCH_SENTENZE_SUCCESS = "SEARCH_SENTENZE_SUCCESS";

//Ritiri const
export const GET_RITIRO = "GET_RITIRO";
export const GET_RITIRO_SUCCESS = "GET_RITIRO_SUCCESS";
export const GET_LIST_RITIRI = "GET_LIST_RITIRI";
export const GET_LIST_RITIRI_SUCCESS = "GET_LIST_RITIRI_SUCCESS";
export const SEARCH_RITIRI = "SEARCH_RITIRI";
export const SEARCH_RITIRI_SUCCESS = "SEARCH_RITIRI_SUCCESS";

//Frodi const
export const GET_FRODE = "GET_FRODE";
export const GET_FRODE_SUCCESS = "GET_FRODE_SUCCESS";
export const GET_LIST_FRODI = "GET_LIST_FRODI";
export const GET_LIST_FRODI_SUCCESS = "GET_LIST_FRODI_SUCCESS";
export const SEARCH_FRODI = "SEARCH_FRODI";
export const SEARCH_FRODI_SUCCESS = "SEARCH_FRODI_SUCCESS";

//Norme USA const
export const GET_NORMAUSA = "GET_NORMAUSA";
export const GET_NORMAUSA_SUCCESS = "GET_NORMAUSA_SUCCESS";
export const GET_LIST_NORMEUSA = "GET_LIST_NORMEUSA";
export const GET_LIST_NORMEUSA_SUCCESS = "GET_LIST_NORMEUSA_SUCCESS";
export const SEARCH_NORMEUSA = "SEARCH_NORMEUSA";
export const SEARCH_NORMEUSA_SUCCESS = "SEARCH_NORMEUSA_SUCCESS";

//Auth const
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';

//Sticky
export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE = 'NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS = 'FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS = 'UPDATE_ALL_NOTES_SUCCESS';

//Contact
export const GET_All_CONTACT_SUCCESS = 'GET_All_CONTACT_SUCCESS';
export const ON_ADD_CONTACT_SUCCESS = 'ON_ADD_CONTACT_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
